# -*- coding: utf-8 -*-
"""Untitled133.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1osiB-9mtLMgjwKgT038uQo39YEaCe4DJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/titanic.csv')

print(df.head())

print(df.info())
print(df.describe())

print(df.isnull().sum())

plt.figure(figsize=(10, 6))
sns.heatmap(df.isnull(), cbar=False, cmap='viridis')
plt.title('Missing Values Heatmap')
plt.show()

plt.figure(figsize=(14, 10))
for i, col in enumerate(['Age', 'Fare']):
    plt.subplot(2, 2, i+1)
    sns.histplot(df[col].dropna(), kde=True)
    plt.title(f'Distribution of {col}')
plt.tight_layout()
plt.show()

plt.figure(figsize=(14, 10))
for i, col in enumerate(['Survived', 'Pclass', 'Sex']):
    plt.subplot(2, 2, i+1)
    sns.countplot(data=df, x=col)
    plt.title(f'Count Plot of {col}')
plt.tight_layout()
plt.show()

sns.pairplot(df[['Age', 'Fare', 'Pclass', 'Survived']].dropna(), hue='Survived')
plt.show()

numerical_df = df.select_dtypes(include=['number'])

plt.figure(figsize=(10, 6))
corr = numerical_df.corr()
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

plt.figure(figsize=(14, 10))
for i, col in enumerate(['Age', 'Fare']):
    plt.subplot(2, 2, i+1)
    sns.boxplot(data=df, y=col)
    plt.title(f'Boxplot of {col}')
plt.tight_layout()
plt.show()